### ISSUE TITLE
Give CivicActions group members access to this repo

### ISSUE THREAD

**Issue by Tom-Camp** [CivicActions/ssp-toolkit#6]
Should this repo be accessible to everyone in the CA group or possibly public?

**Comment by openprivacy** [comment]
It is public (and should be). Do you see different?

**Comment by Tom-Camp** [comment]
It is public and accessible, but Jira was blocking links. Apparently, Jira needed specific perms in order to create the links in the IRP ticket.

**Comment by openprivacy** [comment]
@Tom-Camp should this be closed?

**Comment by Tom-Camp** [comment]
Yes.

**Comment by openprivacy** [comment]
clean up
